// These interfaces strictly mirror the JSON structures generated by our Go backend.
// If a Go developer changes a field name, TypeScript will instantly catch it here.

export interface Metadata {
  inference_time_ms: number;
  model_version: string;
  timestamp: string;
}

export interface EmotionData {
  dominant_emotion: string;
  confidence: number;
  probabilities: Record<string, number>;
}

export interface APIResponse<T = EmotionData> {
  status: "success" | "error";
  message: string;
  data: T | null;
  errors?: Record<string, string[]>;
  code: string;
  request_id: string;
  metadata: Metadata;
}

export interface BatchFaceResult {
  index: number;
  dominant_emotion: string;
  confidence: number;
  probabilities: Record<string, number>;
}

export interface BatchData {
  face_count: number;
  results: BatchFaceResult[];
}

export interface BatchAPIResponse extends Omit<APIResponse, "data"> {
  data: BatchData | null;
}
